Revert "Make box and value month feedback questions optional"
This reverts commit 7d6ece8467905e9aa98c6a99f8034e52614f46ca.

Since this is causing a problem with inserting NULL values into the DB:

  OperationalError: (_mysql_exceptions.OperationalError) (1366, "Incorrect
  integer value: 'None' for column 'cheese_box_1to5' at row 1")