Fix Flask-Admin Python error on model edit
Producing error:
  ...flask_admin/contrib/sqla/fields.py", line 299, in get_pk_from_identity
  ValueError: too many values to unpack

Possibly introduced in last commit by with upgrade to SQLAlchemy:
  -Flask-Migrate==2.0.4
  +Flask-Migrate==2.1.1

See: https://github.com/flask-admin/flask-admin/issues/1583