Work around strftime() exception for dates < 1900
Add Wtf validators on db.Date fields so that dates prior to 1900
cannot be entered, since it produces this error when rendering:

  ValueError: year=X is before 1900; the datetime strftime() methods require year >= 1900

in templates that use strftime().

See FlaskAdmin issue: https://github.com/flask-admin/flask-admin/issues/987

Also: https://stackoverflow.com/questions/10263956/use-datetime-strftime-on-years-before-1900-require-year-1900